# This is unfortunately a hardcoded path in bazel:
# See https://github.com/bazelbuild/bazel/issues/7056 for the tracking issue
package_group(
    name = "function_transition_whitelist",
    packages = [
        "//...",
    ],
)
