cc_library(
    name = "hello-greet",
    srcs = ["src/hello-greet.cc", "include/hello-greet.h"],
    hdrs = ["include/hello-greet.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

