
cc_library(
    name = "lib",
    srcs = glob(["src/*.cpp", "include/**/*.h"]),
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
