cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//module1:lib",
        "//module2:lib",
        "//module3:lib",
        "//module4:lib",
        "//module5:lib",
    ],
)
