cc_library(
    name = "lib",
    srcs = ["lib.cpp"],
    hdrs = ["lib.h"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
    deps = [
        # "//some/sub/package/path:cc_proto_lib",
        "//some/sub/package/path/proto_pkg:cc_proto_pkg",
    ],
)
