cc_library(
    name = "lib",
    srcs = [
        "lib.cpp",
        "lib.h",
    ],
    hdrs = ["lib.h"],
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
    deps = ["//some/sub/package/path/proto_pkg:cc_proto_pkg"],
)
